name: tortho_opti
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.8
  - numpy=1.24
  - tqdm
  - plyfile=0.8.1
  - pip=22.3.1
  - pytorch=2.4.1
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - fused-ssim
      - shapely
      - matplotlib
